#!/usr/bin/env q

/
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
\

fibs: {[cond] -1_{x,sum -2#x}/[cond; 1 1]}
seq: fibs[{(last x) < 4000000}]                  
sum seq where not seq mod 2
\\
